-- Сид справочников из get_phones
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Анапа АЗС Газпром','Анапа АЗС Газпром','АЗС Газпром, ул. Кольцевая 19','https://yandex.ru/navi/-/CDGXeVPI');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Анапа (Анапское шоссе 5)','Анапа','ул.Анапаское шоссе 5,  "Вкусно и точка"','https://yandex.ru/navi/-/CDGLIVky');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Анастасиевская (трасса)','Анастасиевская','трасса, ост. "Поворот на Анастасиевскую"','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Армавир (отель Кавказ)','Армавир','отель Кавказ','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Астрахань ост. "Солянка"','Астрахань ост.','Николаевское шоссе 2Д, кафе - магазин "Экспресс"','https://yandex.ru/navi/-/CDSwfMiF');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Богучар АЗС Ронефть','Богучар АЗС Ронефть','АЗС Роснефть, Дзержинского 243','https://yandex.ru/navi/-/CDg85P8-');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Воронеж Остужева51(Газпромнефть)','Воронеж Остужева51','АЗС Газпромнефть, Остужева 51','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Воронеж (АЗС Газпронефть)','Воронеж','АЗС Газпромнефть, Остужева 51','https://yandex.ru/navi/-/CDG2J2pG');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Дивное ОП','Дивное ОП','Остановочный пункт','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Евпатория ж/д','Евпатория ж/д','площадь жд вокзала','https://yandex.ru/navi/-/CDGLMAOm');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ипатово (АЗС Лукойл)','Ипатово','АЗС Лукойл, ул. Полевая 2','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Каменск-Шахтинский (музей СССР)','Каменск-Шахтинский','Музей легенды СССР','https://yandex.ru/navi/-/CDg8uOYQ');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Каменск-Шахтинский (р-к Америка)','Каменск-Шахтинский','Музей легенды СССР','https://yandex.ru/navi/-/CDg8uOYQ');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Керчь (Чкалова 44)','Керчь','ул.Чкалова 44 ост. Детская больница','https://yandex.ru/navi/-/CDG2r4lT');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Керчь (стадион)','Керчь','ост. Стадион, ул. Маршала Еременко, 9','https://yandex.ru/navi/-/CDWTJ8zU');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Красногвардейское ОП','Красногвардейское ОП','Остановочный пункт, ул. Дружбы, 8','https://yandex.ru/navi/-/CDSwfO5D');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Краснодар  ул.Суворова, 2/1','Краснодар  ул.Суворова, 2/1','АЗС Газпром, ул.Суворова, 2/1','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Краснодар (Лукойл)','Краснодар','АЗС Лукойл, ул. Крылатная 2/1','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Кропоткин ост. "кафе Лезгинка"','Кропоткин ост.','ост. "кафе Лезгинка"','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Минеральные воды (аэропорт)','Минеральные воды','парковка аэропорта','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Москва (Лесопарковая)','Москва','ст. метро Лесопарковая, парковка автобусов','https://yandex.ru/navi/-/CDGXaMId');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Москва "Саларьево"','Москва','ст. метро Саларьево, "Автовокзал «Саларьево»"','https://yandex.ru/maps/-/CPSOyDJC');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Москва АВ "Битца"','Москва АВ','ст. метро Лесопарковая, парковка автобусов','https://yandex.ru/navi/-/CDGXaMId');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Москва АВ "Южные ворота"','Москва АВ','АВ "Южные ворота"','https://yandex.ru/navi/-/CDWqMCNA');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Невинномыск "АЗС Роснефть"','Невинномыск','АЗС Роснефть, ул. Гагарина 2','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Новоалександровск ("Пятерочка")','Новоалександровск','магазин Пятерочка ул. Победы, 19','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Павловск АС','Павловск АС','Автостанция','https://yandex.ru/navi/-/CDg8uDnQ');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ростов на Дону (ТЦ Мега)','Ростов на Дону','ТЦ Мега, ост. Аксайский поворот','https://yandex.ru/maps/-/CPSOfU89');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ростов-на-Дону','Ростов-на-Дону','Главный автовокзал, проспект Сиверса, 3, платформа №2','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Саки АЗС Атан Евпаторийское ш79Б','Саки АЗС Атан Евпаторийское ш79Б','АЗС Атан Евпаторийское ш79Б','https://yandex.ru/navi/-/CDsCjF6j');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Севастополь (сады)','Севастополь','Ост. Сады, ул.2-ой Обороны','https://yandex.ru/navi/-/CDWBALzB');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Симферополь ж/д (парковка Пуд)','Симферополь ж/д','парковка базы Артек, напротив жд вокзала','https://yandex.ru/navi/-/CDG2nOIC');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Симферополь пр-кт Победы 237','Симферополь пр-кт Победы 237','троллейбусное кольцо, пр-кт Победы 237','https://yandex.ru/navi/-/CDWBEV3Y');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Славянск-наКубани ост.Автовокзал','Славянск-наКубани ост.Автовокзал','ост.  "Автовокзал",  магазин "Цветы"','https://yandex.ru/navi/-/CDGxbM5C');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Сочи (аэропорт)','Сочи','Стела Олимпийские  кольца','https://yandex.ru/navi/-/CDGpVK7n');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Сочи (пост Мамайка)','Сочи','Въездной пост ГИБДД "Мамайка" , ул. Виноградная, 272','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ставрополь АВ','Ставрополь АВ','Автовокзал, ул. Маршала Жукова, 27','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тамань (АЗС Лукоил)','Тамань','АЗС Лукойл','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тбилисская (АЗС "Роснефть")','Тбилисская','АЗС Лукойл, трасса , 252-й км','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Темрюк АЗС Роснефть','Темрюк АЗС Роснефть','АЗС Роснефть, ул.Евгения Шапова, 25','https://yandex.com/maps/-/CDTJyWLK');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тимашевск ост. "м-н Магнит"','Тимашевск ост.','ост. напротив Автовокзала, магазин Магнит, ул. Братьев Степановых, 20','https://yandex.ru/navi/-/CDG2rLJ4');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тула (Музей Оружия)','Тула','парковка туристических автобусов Музея Оружия, Оружейный переулок- напротив ресторана Сударь','https://yandex.com/navi/-/CDg8fB-8');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тула (трасса)','Тула','трасса  192 км, в сторону Ростова, пост ДПС ,памятник старому москвичу','https://yandex.ru/navi/-/CDSnNEyz');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Тула (ост.Кирпичный завод)','Тула','автобусная остановка  "Кирпичный завод", Городской пер., 46','https://yandex.ru/maps/-/CPSOJ28-');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Усть-Лабинск (пост ДПС)','Усть-Лабинск','пост ДПС','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Феодосия  АЗС «Атан»','Феодосия  АЗС','Керченское шоссе, ост. санаторий Украина','https://yandex.ru/navi/-/CDG2rAI1');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Феодосия (ост.пансионат Украина)','Феодосия','Керченское шоссе, ост. санаторий Украина','https://yandex.ru/navi/-/CDG2rAI1');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Шахты (трасса)','Шахты','трасса м4,  поворот на Шахты','https://yandex.ru/maps/-/CPSO6S2F');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Элиста АС','Элиста АС','Автостанция, Привокзальная площадь 1','https://yandex.ru/navi/-/CDSwf4N5');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ялта АВ','Ялта АВ','Автовокзал, ул. Московская 8','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Яшкуль','Яшкуль','Автостанция, ул. Клыкова, 25','');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Геленджик (Магнит у автовокзала)','Геленджик','Магнит у автовокзала (Кирова 125)','https://yandex.ru/navi/-/CDGX4AN1');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Новороссийск (Вкусно и Точка)','Новороссийск','парковка ресторана "Вкусно и Точка" ул. Мира 3','https://yandex.ru/navi/-/CDSAy6zH');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Краснодар ТЦ "Бауцентр"','Краснодар ТЦ','Ростовское шоссе 28 ост. ТЦ БАУЦЕНТР','https://yandex.com/navi/-/CDXCaUin');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Алушта (АЗС Атан)','Алушта','АЗС АТАН ул.Симферопольская 42 А','https://yandex.ru/maps/-/CHwUzWjG');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Ялта (ул Московская)','Ялта','Автовокзал напротив троллейбусных касс','https://yandex.ru/maps/-/CHxTfCMA');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Белгород (автовокзал)','Белгород','ул.Урожайная м-н "Смешные цены"','https://yandex.ru/maps/-/CLTmm8JO');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Курск " ТЦ Европа"','Курск','парковка ТЦ Европа','https://yandex.ru/maps/-/CLTm5DJ2');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Анапа АЗС Газпромнефть','Анапа АЗС Газпромнефть','','https://yandex.ru/navi/-/CDGXeVPI');
INSERT IGNORE INTO stops (station, city, address, map_url) VALUES ('Темрюк  (ост. Столовая)','Темрюк','','https://yandex.com/maps/-/CDTJyWLK');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('018','А018ТУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('474','А474ЕУ92','+79781267723');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('473','А743ЕУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('723','A723ЕУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('634','А634ЕУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('034','А034ТУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('986','C986EУ197','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('632','А632ЕУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('995','Белый Ютонг М995РВ82','+79787659556');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('743','А743ЕУ92','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('340','Белый Ютонг E340KУ82','+79780549307');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('322','Белый Ютонг Р322МТ82','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('923','Белый Ютонг Р923АТ82','');
INSERT IGNORE INTO buses (code, plate, driver_phone) VALUES ('783','Белый Неоплан Р783ЕО178','');
