<?php /** @var array $rows $top $users */
$actionNames=['group.preview'=>'Предпросмотр сообщения','campaign.overview'=>'Проверка результатов рассылки','channels.states'=>'Проверка каналов','campaign.send'=>'Отправка рассылки','groups'=>'Загрузка групп рейса','campaign.enqueue'=>'Постановка в очередь','channels.queue'=>'Состояние очереди','wa.accounts'=>'Аккаунты WhatsApp','auth.login'=>'Вход в панель','channels.delays'=>'Настройка темпа отправки','manifest.pull'=>'Загрузка ведомости','manifest.update'=>'Изменение ведомости','chat.threads'=>'Открытие списка чатов','chat.messages'=>'Открытие переписки','settings.save'=>'Сохранение настроек'];
$resultNames=['started'=>'запущено','success'=>'успешно','failure'=>'ошибка'];
$actionLabel=fn($a)=>$actionNames[$a]??$a;
?>
<div class="page-head"><div><div class="eyebrow">Контроль и аналитика</div><h1>Журнал действий</h1><div class="sub">кто и какими функциями пользовался</div></div></div>
<?php if (!$auditReady): ?><div class="notice warning">Журнал временно недоступен. Обратитесь к администратору.</div><?php endif; ?>
<div class="card"><form class="filters" method="get"><input type="hidden" name="p" value="audit"><select name="user"><option value="0">Все сотрудники</option><?php foreach($users as $u): ?><option value="<?= (int)$u['id'] ?>" <?= $user===(int)$u['id']?'selected':'' ?>><?= e($u['name']) ?></option><?php endforeach; ?></select><input name="action" value="<?= e($action) ?>" placeholder="Функция"><input type="date" name="from" value="<?= e($from) ?>"><input type="date" name="to" value="<?= e($to) ?>"><button class="btn primary">Показать</button></form></div>
<?php if ($top): ?><div class="card"><h2>Часто используемые функции</h2><div class="audit-top"><?php foreach($top as $t): ?><div><span><?= e($actionLabel($t['action'])) ?></span><strong><?= number_format((int)$t['total'],0,'',' ') ?></strong><small class="muted">раз</small></div><?php endforeach; ?></div></div><?php endif; ?>
<div class="card"><h2>Последние действия</h2><?php if (!$rows): ?><p class="muted">За выбранный период действий нет.</p><?php else: ?><div class="logfeed"><?php foreach($rows as $r): ?><div class="lg-row"><div class="lg-top"><span class="lg-time"><?= e(date('d.m.Y H:i',strtotime($r['created_at']))) ?></span><span class="badge <?= $r['result']==='failure'?'err':($r['result']==='started'?'warn':'ok') ?>"><?= e($resultNames[$r['result']]??$r['result']) ?></span><strong title="<?= e($r['action']) ?>"><?= e($actionLabel($r['action'])) ?></strong><span class="muted"><?= e($r['actor_name']) ?></span><?php if($r['entity_type']): ?><span class="faint"><?= e($r['entity_type']) ?> №<?= (int)$r['entity_id'] ?></span><?php endif; ?></div></div><?php endforeach; ?></div><?php endif; ?></div>
